package com.simplenazmul.service;

import java.sql.Timestamp;
import java.util.List;

import com.simplenazmul.model.User;
import com.simplenazmul.model.UserPic;
import com.simplenazmul.model.UserPicAlbum;

public interface UserPicService {

	void save(UserPic userPic);
	
	void updatePic(UserPic userPic);

	List<UserPic> findByAlbumId(UserPicAlbum albumId);

	List<UserPic> findByUser(User User);

	UserPic findById(int userPictureId);

	void deleteById(int userPictureId);
	
	List<UserPic> findRecent20PicByLoginUserId(int loginUserId);
	
	List<UserPic> findRecent20PicByFriendUserId(int paramUserId);
	
	List<UserPic> findRecent20PicByPublicUserId(int paramUserId);
	
	public String timeAgoFunction(Timestamp time);
	
	String findAutoGeneratedPicName(int pictureId);
	
	UserPic findByAutoGeneratedPicName(String pictureNameAutoGenerated);
}
